apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend
  namespace: tispace
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-lvm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: tispace
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backend
  namespace: tispace
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "services"
      - "persistentvolumeclaims"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "delete"
      - "update"
      - "patch"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backend
  namespace: tispace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backend
subjects:
  - kind: ServiceAccount
    name: backend
    namespace: tispace
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: tispace
  name: backend-env
data:
  default-rootfs-image-tag: latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: tispace
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend
      containers:
      - name: backend
        image: tispace/backend:latest
        imagePullPolicy: IfNotPresent
        workingDir: /workdir
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: google-client-id
              name: google-client
        - name: DEFAULT_ROOTFS_IMAGE_TAG
          valueFrom:
            configMapKeyRef:
              key: default-rootfs-image-tag
              name: backend-env
        - name: LXD_SERVER_URL
          valueFrom:
            configMapKeyRef:
              key: lxd-server-url
              name: backend-env
        - name: LXD_CLIENT_CERT
          value: /etc/tispace/lxd-client.p12
        - name: LXD_STORAGE_POOL_MAPPING
          valueFrom:
            configMapKeyRef:
              key: lxd-storage-pool-mapping
              name: backend-env
        - name: EXTERNAL_IP_POOL
          valueFrom:
            configMapKeyRef:
              key: external-ip-pool
              name: backend-env
        - name: EXTERNAL_IP_PREFIX_LENGTH
          valueFrom:
            configMapKeyRef:
              key: external-ip-prefix-length
              name: backend-env
        - name: CPU_OVERCOMMIT_FACTOR
          valueFrom:
            configMapKeyRef:
              key: cpu-overcommit-factor
              name: backend-env
        - name: MEMORY_OVERCOMMIT_FACTOR
          valueFrom:
            configMapKeyRef:
              key: memory-overcommit-factor
              name: backend-env
        volumeMounts:
        - name: workdir
          mountPath: /workdir
        - mountPath: /etc/tispace
          name: lxd-client-cert
      volumes:
      - name: workdir
        persistentVolumeClaim:
          claimName: backend
      - name: lxd-client-cert
        secret:
          defaultMode: 420
          secretName: lxd-client-cert
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: tispace
  labels:
    app: backend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend
  type: ClusterIP
