apiVersion: v1
kind: ConfigMap
metadata:
  namespace: tispace
  name: frontend-env
data:
  nextauth-url: https://tispace.dev
  next-public-server-url: https://api.tispace.dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: tispace
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: tispace/frontend:latest
        imagePullPolicy: IfNotPresent
        command:
        - "sh"
        - "-c"
        - |
          ls ./.next/static/chunks/pages/index* | xargs  sed -i "s|G.env.NEXT_PUBLIC_SERVER_URL|\"$NEXT_PUBLIC_SERVER_URL\"|g" && "node_modules/.bin/next" "start"
        ports:
        - containerPort: 3000
        env:
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: google-client
              key: google-client-id
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: google-client
              key: google-client-secret
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: google-client
              key: secret
        - name: NEXTAUTH_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-env
              key: nextauth-url
        - name: NEXT_PUBLIC_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-env
              key: next-public-server-url
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: tispace
  labels:
    app: frontend
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: frontend
  type: ClusterIP
