name: Frontend

on: [push, pull_request]

defaults:
  run:
    working-directory: ./app

jobs:
  lint:
    strategy:
      matrix:
        node-version: [ 12.x ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn lint

